### ISSUE TITLE
Server version 15 or lower is required

### ISSUE THREAD

**Issue by fabianWrede** [nextcloud/end_to_end_encryption#117]
Hi,
I use Nextcloud 17 and get the message that the app requires Nextcloud 15 or lower. In the appinfo/info.xml the version is actually set to 18: `<nextcloud min-version="18" max-version="18" />`

Should/can I use this app somehow with version 17?

Thanks

**Comment by JimLoose** [comment]
superstrange behavoir @nextcloud

it looks like you dropped the development for this important feature which was already working.
Would love to hear the team about this issue! (Of course all your apps still have it implemented)

**Comment by nautik1** [comment]
Would love to know more about it too!

**Comment by LukasReschke** [comment]
@rullzer ^

**Comment by wiswedel** [comment]
@rullzer NC 18 is in the starting blocks, let's get this released, too

**Comment by rullzer** [comment]
This is not production ready right now anyway. So just change the max version in info.xml for now.
I have it on my list but it is low on that list.

**Comment by ad2003** [comment]
Hi there - I am also a little bit confused. I am running Nextcloud 17 latest. e2ee shows up as not comatible / outdated. It works between android and desktop on Win. What is the current state?
As this is a major feature of Nextcloud it is very important and I think it is a bit strange, that the current state is so foggy... When it works it works great (getting a problem on linux though - no encryption on cloud at all...

**Comment by frake65** [comment]
Very disappointed that this actually does not really work for me - NC 18 and latest MAC client 2.6.2. need this for production urgently (need to encrypt that data - and it had worked already with earlier versions) - so what is the deal? Anything where one could help  with?
When installed and some files from client are up to be synced, the client seems to prepare for upload forever. Force sync does not give any solution either.

**Comment by georgehrke** [comment]
Closing, because all branches have the correct version at the moment.

stable15:
https://github.com/nextcloud/end_to_end_encryption/blob/8c632c3c66661976d7b4978dfa5025fc8b8a5da6/appinfo/info.xml#L21

stable16:
https://github.com/nextcloud/end_to_end_encryption/blob/9d26aed801829f79584b759669d80a543e3df7fa/appinfo/info.xml#L21

stable17:
https://github.com/nextcloud/end_to_end_encryption/blob/060762679ecc9589b874b8738561c50bda6ec848/appinfo/info.xml#L21

stable18: 
https://github.com/nextcloud/end_to_end_encryption/blob/69f9f2498c75a988f21e5fb3e2eb7349c533bba4/appinfo/info.xml#L21

master:
https://github.com/nextcloud/end_to_end_encryption/blob/39b00b27aaeee1e3361f206d5d52a404f78f99f6/appinfo/info.xml#L21
