### ISSUE TITLE
impossible to store mnemonic and activate it on other hosts

### ISSUE THREAD

**Issue by boistordu** [nextcloud/end_to_end_encryption#123]
hi,
I'm going to group several problems into one and I'm sorry for that by advance.
I've just seen tonight that the end to end encryption module wasn't maked as untested in the store and was under the official category so, normally fully tested, fully functional.
So I've installed it on one of my external instance. 

First, I would like to mention that the lack of documentation with screenshot for how it is supposed to happen and work is really annoying because it causes part of my problem of not knowing to what to hope for a normal process ot happen.

So After that, on one of my client, when I started the windows client it showed me a popu with a passphrase. I copy paste it. The phrase, and I think this is importantand part of the problem, was centered in the popup so with a lot of space before and between. 

I tried to put it on other windows hosts. For that, I just restart the client on those hosts which asked me for the passphrase, during that operation the connection with the instance was apparently not working since it was grayed. I try to paste-copy and nothing, it kept asking me for the passphrase.
=> I guess it should not happen and it is not supposed to behave like that if the copy paste is right (which is why I've mentioned the multiple spaces before. 

All the windows host are win 10 pro up to date with client: 20200217

So in the end I canceled the popup and then connection was starting. But if I go to the "show nmemonic" it prints nothing, which I guess means that it did not sotre the E2E passphrase.

So I've tried to disable and re-enable the app, apparently it does not reset the passphrase.
I've tried to uninstalled and reinstalled the app, same result.

As I can see in the windows client app, there is an option to encrypt a folder, but when it is encrypted there is no option to unencrypt the folder.
another thing is that, if I play a little bit in the same menu and select and unselect folders, apparently it the folder is not noted as encrypted anymore. 

Also I've search where to get the mnemonic on the web interface and I foudn nothing.

1/ there seem to be a bug with the popup window and how it prints the mnemonic so where can I regenerate a passphrase?
2/ Where in the webinterface can I just delete all information about E2E and start over?
3/ why isn't there any unencrypt folder or files in the menu? 
4/  where is the technical documentation of this app? 

Thanks in advance for all the help you can give me but I would appreciate at least that you would give me the way to delete all traces of this app if it is actually buggy and not working correctly. And sorry if it is a duplicate but the other posts talking about keys and passphrase reinit is way more advanced that what I'm asking. I shouldn't be as a user confront to any keys removal and there should be an obvious menu at least to revoke then all passphrase or keys or whatever in the security tab of the user.

**Comment by georgehrke** [comment]
> I'm going to group several problems into one and I'm sorry for that by advance.

If you already know that you should create one issue per problem, please do so from the beginning. Thx ;) 

> First, I would like to mention that the lack of documentation with screenshot for how it is supposed to happen and work is really annoying because it causes part of my problem of not knowing to what to hope for a normal process ot happen.

Please open an enhancement request in https://github.com/nextcloud/documentation

> So After that, on one of my client, when I started the windows client it showed me a popu with a passphrase. I copy paste it. The phrase, and I think this is importantand part of the problem, was centered in the popup so with a lot of space before and between.
> 
> I tried to put it on other windows hosts. For that, I just restart the client on those hosts which asked me for the passphrase, during that operation the connection with the instance was apparently not working since it was grayed. I try to paste-copy and nothing, it kept asking me for the passphrase.
=> I guess it should not happen and it is not supposed to behave like that if the copy paste is right (which is why I've mentioned the multiple spaces before.
>
> So in the end I canceled the popup and then connection was starting. But if I go to the "show nmemonic" it prints nothing, which I guess means that it did not sotre the E2E passphrase.

As you stated yourself, this is a problem of the desktop Client, so please open a detailed bug report in the corresponding repository: https://github.com/nextcloud/desktop/

Since it's end to end encryption and the server is not supposed to be able decrypt it, it never knows the passphrase.

> As I can see in the windows client app, there is an option to encrypt a folder, but when it is encrypted there is no option to unencrypt the folder.

Again, please open a feature request in https://github.com/nextcloud/desktop/.
As a quick workaround: Just create a new folder outside the encrypted one and move the files there, that should sync the unencrypted to the server.


---

> 1/ there seem to be a bug with the popup window and how it prints the mnemonic so where can I regenerate a passphrase?

Only the client can do that. Since you were talking about desktop clients, please open a ticket there: https://github.com/nextcloud/desktop/

> 2/ Where in the webinterface can I just delete all information about E2E and start over?

There is no way to reset the app. If you delete all encrypted folders on all clients, it should be in its initial state though.

> 3/ why isn't there any unencrypt folder or files in the menu?

Again, you seem to be referring to the desktop client here. Please open a feature request there: 
https://github.com/nextcloud/desktop/

> 4/ where is the technical documentation of this app?

As mentioned above, please open a ticket in the documentation repo.
