### ISSUE TITLE
filesnames are not encrypted

### ISSUE THREAD

**Issue by JimLoose** [nextcloud/end_to_end_encryption#275]
filesnames are not encrypted with E2EE

At least a notification about that would be great 👍

**Comment by purdieb** [comment]
The name of the top level folder isn't encrypted, but the names of all files stored within should be encrypted.

Given that file synchronization is still working for you, I doubt that this is a bug with specifically E2EE in either the client or the server app. It is far more likely that this is a consequence of using E2EE with server side encryption (as you mentioned in #274). It is worth noting that Nextcloud's server side encryption does not encrypt file names.

I am not familiar with how nextcloud's client/server behave when trying to use E2EE with server side encryption, so I don't know exactly how the server/client deal with this case.

You are definitely correct about notifying the user in this case; if E2EE isn't functional due to server side encryption then the client should notify the user.

**Comment by JimLoose** [comment]
purdieb, thank you! Files are still visible in plaintext in the database.
I'll check the case with server side encryption on

**Comment by eibex** [comment]
E2EE and server-side encryption are not compatible and shouldn't be used together as mentioned in the README.
