### ISSUE TITLE
Unlock file

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/end_to_end_encryption#30]
https://github.com/nextcloud/end_to_end_encryption/blob/master/doc/api.md#unlock-file

Change : unlock the file again after the file and the meta data was updated correctly, to unlock the file after send metadata ... 

The token needs to be added to the header, see example below (for me this is unused and nonsense)

look for detail : https://github.com/nextcloud/end_to_end_encryption/issues/29#issuecomment-352439232

**Comment by tobiasKaminsky** [comment]
I hopefully explained in detail and with examples why we need to have payload and metadata always in sync here https://github.com/nextcloud/end_to_end_encryption/issues/29#issuecomment-352481251

P.S: saying that something is nonsense is quite a bit harsh in my opinion. Maybe this approach cannot work reliable on iOS (due to limitations on the OS), but your approach can (and probably will) lead to data corruptions.

**Comment by schiessle** [comment]
as explained the whole purpose of the lock is to make two separate calls "send the file and send the metadata" one atomic operation. So the lock need to stay until both operations are finished. Otherwise the lock is completely useless.
