### ISSUE TITLE
Files inside the encrypted folder root are not encrypted

### ISSUE THREAD

**Issue by Kurgan-** [nextcloud/end_to_end_encryption#382]
### Steps to reproduce
1. install e2ee app on server
2. enable e2ee on client
3. create a folder in nextcloud app (call it e2ee-test)
4. set the folder (currently empty) as encrypted (a padlock is shown)
5. from the client pc, copy a file to the encrypted folder (from Desktop to the nextcloud directory, under e2ee-test) For example, copy ~/Desktop/test.pdf  to ~/nextcloud/e2ee-test/test.pdf
6. the file gets synced to the server without errors
7. ssh to the the server, go into data directory, locate the e2ee-test folder, look into it
8. you'll find the file you copied has retained its original name and contents, it's not encrypted at all

This behavior is repeatable, I have copied some files (pdf, jpg) and they are synced to the server but not encrypted.

If I create a folder inside the encrypted folder (e2ee-test/innerfolder/) then that folder gets encrypted. Its name on the server is not the same as on the PC, and its contents have garbled names and data.

### Expected behaviour

The files I copy inside the e2ee-test folder get a random name and are encrypted.

### Actual behaviour

The files I copy inside the e2ee-test folder are not encrypted at all, their names and contents are the same as the original ones.
The subfolders (and files within them) I create under the e2ee-test folders are actually encrypted as expected.

### Client configuration

Client version 3.6.4 on Linux Mint 21

### Server configuration

Linux Debian 11
Apache2 2.4.54
Mariadb 10.5.15
Php 8.0.26
Nextcloud 25.0.2 updated multiple times without issues, installed from the tarfile from nextcloud site (not packaged)
E2ee app version 1.11.1
No integrity errors on nextcloud server.
No other form of encryption active.
No external storage in use
No external user backend (I have just 2 local users)
No errors in apache error.log
Nextcloud log is 60 Mbytes and there are no errors that I can see that are related to this issue.

**List of activated apps:**

<details>
<summary>Nextcloud apps</summary>

```
Enabled:
  - activity: 2.17.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.2
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - end_to_end_encryption: 1.11.1
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - files_mindmap: 0.0.27
  - suspicious_login
  - twofactor_totp
  - user_ldap

```

</details>

**Comment by robolange** [comment]
I can confirm this issue. I ran into the same issue starting about a week ago. I don't know when exactly the issue started, because it's been a while since I've uploaded a new or updated file to my encrypted folder, but I suspect it was sometime around the upgrade to v25. The issue manifested in v25.0.1-3 for me, using e2ee app 1.11.0 and 1.11.1, and Linux desktop client 3.6.4-6. Very similar configuration as above, but with PHP 7.4.33 (which, yeah, I know I need to update it).

The first symptom of the issue was that I was not able to delete any files, from any client. The server logs indicated that this was because of encryption, which didn't make sense to me because the files I was trying to delete were not encrypted. Some posts online suggested disabling the e2ee app, which I did, and I was able to delete the files. However, after subsequently re-enabling the e2ee app, resetting my key (and allowing it to delete the old e2ee files), creating a new key, and creating a new encrypted folder, I noticed that a test image I uploaded from the Linux desktop client to the encrypted folder had its name and thumbnail visible in the webapp. Subsequent examination showed the file had been uploaded in cleartext to the "encrypted" folder, without any warnings by the client.

I hope this issue is taken seriously and acted on quickly. An encryption app failing silently and uploading cleartext files is pretty much the worst case scenario. This can get people killed in the wrong circumstances.

**Comment by Kurgan-** [comment]
@robolange Thanks for commenting. I can add that in my case it was the first time I enabled E2EE, so my issue is not from an upgrade, but from a new install (to be more precise: I have upgraded nextcloud many times, but only installed E2EE when I was already at 25.0.2.

Also I have not experienced your issue with deleting files outside of the encrypted folders, but this is probably because I had not upgraded a system where encrypted folders were already in use, as you did.

If E2EE is currently not only malfunctioning inside of ecnrypted folders, but also causing issues outside of them, then I'd say it's better I just stop using it.

**Comment by meonkeys** [comment]
Does the desktop client agree that encryption is _enabled_ for the account? Note the differences in these two screenshots:

![Screenshot from 2023-02-24 16-13-05](https://user-images.githubusercontent.com/50639/221324084-5c4106f6-6e95-4c43-bf51-5a14ed67e351.png)

![Screenshot from 2023-02-24 16-13-18](https://user-images.githubusercontent.com/50639/221324093-cc80657c-4795-440a-9a1b-98270b5367df.png)

When I was seeing the "supported" message (in a blue box), files were not being encrypted server-side. Once I got the green "enabled" box, files _are_ being encrypted.

Another question: did you try with a mobile client too? If so I'm curious if that worked or not.

**Comment by Kurgan-** [comment]
Yes, encryption is enabled and in fact the inner folders, as I stated, are indeed encrypted.

But after updating the client to 3.7.3 and the server to 25.0.4, it works properly. I had not tested anymore since I filed the bug, then I came here to check again now, and now it works. The E2EE app itself is still 1.11.1 as it was before.

So now it works, but I don't now why and I'm not sure why and if it will continue working properly. I cannot trust such a system.
