### ISSUE TITLE
Broken UI when defining a group who may use the app

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/end_to_end_encryption#526]
The webUI which allows to select which groups may use the app is broken: after defining the group it doesn't show it, but the empty field, and after the reload the field disappears.

1. Select group of users
![image](https://github.com/nextcloud/end_to_end_encryption/assets/5199030/6f5ac944-ad9a-4c84-af43-45e266054485)

2. Click Save

3. Reload page

4. Observe empty field
![image](https://github.com/nextcloud/end_to_end_encryption/assets/5199030/56976f48-f674-48ca-90c4-2f5e261d142a)

5. Click Save

6. Observe undefined state without any field at all
![image](https://github.com/nextcloud/end_to_end_encryption/assets/5199030/f3839894-cad3-4580-b849-cef183b0bb17)

**Comment by mawumag** [comment]
I can reproduce the bug. More in detail:

1. On first "Save" (using `admin` as input as in the pictures above):
      - The UI **correctly** updates the `oc_appconfig` table in the database.
      - The value for the key `allowed_groups` is now `["admin"]`.
2. On "Refresh":
      - The database entry is correctly queried and registered in an `#initial-state-` element by nextcloud (base64 encoded).
      - The UI seems to be unable to correctly display the groups, it only shows the weird box as per second screenshot by OP.
3. On second "Save":
      - The UI updates the `allowed_groups` property to `[null]`, which leads to a broken UI. If `admin` is (re)added before saving, it will be updated to `[null,"admin"]`, also resulting in a broken UI.

Some additional observations:
- I tried with different groups (such as `test`) and the results are the same.
- If one initially tries to select two groups, say admin and test, the `allowed_groups` property is written to the database as `["admin","test"]` as expected, but the UI seems to be unable to load it at all (spinning wheel in the multiselect box is displayed forever).

Given the above, I suspect the issue lies in the `src/components/AdminSection.vue` logic, but I have not been able to find anything wrong with it so far.

**Comment by mawumag** [comment]
UPDATE:
I also verified that the component correctly pulls the list of allowed groups from the database, and the variables `groups` and `allowedGroups` are correctly assigned.
I can only imagine that the component `NcMultiselect` is not working properly. Indeed, it seems to have been deprecated (see for example https://github.com/nextcloud/server/issues/38145, https://github.com/nextcloud/server/issues/40588).

I have switched `NcMultiselect` to `NcSelect` as suggested in the issues linked above, and everything seems to work properly (it also looks better in my opinion).

I can provide a pull request shortly after some more testing.

**Comment by joshtrichards** [comment]
Thanks @mawumag for looking into and taking care of this!

**Comment by mawumag** [comment]
My pleasure! It might be that some users have a database entry for allowed_groups that is inconsistent (e.g. `[null]`) due to the previous behaviour.

I have not tested what happens with the new UI in this case, but it might be necessary to implement a fix if users report issues.
