### ISSUE TITLE
Lock file API

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/end_to_end_encryption#9]
@schiessle 

If I call Lock API and after I lose the token, the file remains locked and can not be longer locked, return always error 403.

**Comment by schiessle** [comment]
yes, if you lose the token you are lost. That's the responsibility of the client. The server can't free the the lock because the server don't know if the client has finished it's operation and the files are in a useful and consistent state. The client need to make sure that it frees every look after a operation was completed. If the client loses network connection for example it is the responsibility of the client to retry and only free the lock if the operation was successful or the client rolled back it's changes.

**Comment by marinofaggiana** [comment]
now I have issue (lock) with the server of Tobi @tobiasKaminsky it's a problem of my API ?
